version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  job1:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: ruby odd_even.rb

  job2:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Echo message
          command: echo "This is job 2"

  job3:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Echo message
          command: echo "This job 3, this will run on second workflow"

workflows:
  flow1: 
    jobs:
      - job1
      - job2

  flow2: 
    jobs:
      - job3:
          #requires:
            #- job2
